version: '3.8'

services:
  app:
    env_file:
      - .env/compose.env
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ch-network

  db:
    image: postgres:latest
    env_file:
      - .env/compose.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ch-network

volumes:
  pgdata:

networks:
  ch-network:
    driver: bridge